# Generated by Django 4.2 on 2023-04-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
